# location of huggingface dataset
dataset_location=E:/datasets

# location to build the index
index_location=H:/coherepedia

# Cohere API key (used for searches, not for building the index)
cohere_api_key=

# dataset divisor: load 1/divisor of the rows
# so divisor=100 will load 1% of the data for a quick test
divisor=1
